import { promises as fs } from 'fs';
import * as path from 'path';

async function main() {
  const rootDir = path.resolve(__dirname, '..');
  const animalsDir = path.join(rootDir, 'assets/images/animals');
  const outputPath = path.join(rootDir, 'app/services/imageRegistry.ts');

  const files = await fs.readdir(animalsDir);
  const imageFiles = files.filter((file) => file.endsWith('.png'));

  const lines = imageFiles
    .sort()
    .map((file) => `  '${file}': require('../../assets/images/animals/${file}'),`)
    .join('\n');

  const content = `// Auto-generated by scripts/generate-image-registry.ts\nimport type { ImageSourcePropType } from 'react-native';\n\nconst imageRegistry: Record<string, ImageSourcePropType> = {\n${lines}\n};\n\nexport default imageRegistry;\n`;

  await fs.writeFile(outputPath, content);
  console.log(`Generated image registry with ${imageFiles.length} entries.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
