import { promises as fs } from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const AUDIO_EXTENSIONS = ['.mp3', '.wav', '.m4a', '.aac'];

interface AudioFile {
  relativePath: string;
  filename: string;
  key: string;
}

async function scanAudioFiles(dir: string, basePath = ''): Promise<AudioFile[]> {
  const files: AudioFile[] = [];

  try {
    const items = await fs.readdir(dir);

    for (const item of items) {
      const fullPath = path.join(dir, item);
      const relativePath = path.join(basePath, item).replace(/\\/g, '/');
      const stat = await fs.stat(fullPath);

      if (stat.isDirectory()) {
        files.push(...(await scanAudioFiles(fullPath, relativePath)));
      } else if (stat.isFile() && AUDIO_EXTENSIONS.includes(path.extname(item))) {
        files.push({
          relativePath,
          filename: item,
          key: generateKey(relativePath),
        });
      }
    }
  } catch (error) {
    console.warn(`Warning: Could not read directory ${dir}:`, error);
  }

  return files;
}

function generateKey(relativePath: string): string {
  return relativePath
    .replace(/\.(mp3|wav|m4a|aac)$/, '')
    .replace(/\//g, '_')
    .replace(/[^a-zA-Z0-9_-]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');
}

async function main() {
  const rootDir = path.resolve(__dirname, '..');
  const audioDir = path.join(rootDir, 'assets/audio');
  const outputDir = path.join(rootDir, 'app/services');

  console.log('Scanning for audio files...');
  const audioFiles = await scanAudioFiles(audioDir);

  if (audioFiles.length === 0) {
    console.log('No audio files found in assets/audio/');
    return;
  }

  console.log(`Found ${audioFiles.length} audio files`);

  // Generate autoAudioMap.ts
  const audioMapLines = audioFiles
    .sort((a, b) => a.key.localeCompare(b.key))
    .map((file) => `  '${file.key}': require('../../assets/audio/${file.relativePath}'),`)
    .join('\n');

  const audioMapContent = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by scripts/generate-audio-registry.ts
// Run 'npm run map-audio' to regenerate

const audioMap: Record<string, any> = {
${audioMapLines}
};

export { audioMap };
`;

  await fs.writeFile(path.join(outputDir, 'autoAudioMap.ts'), audioMapContent);
  console.log('Generated autoAudioMap.ts');

  // Generate dictionaryAudio.ts
  const dictionaryFiles = audioFiles.filter((f) => f.relativePath.startsWith('dictionary_words/'));
  const dictionaryLines = dictionaryFiles
    .sort((a, b) => a.filename.localeCompare(b.filename))
    .map((file) => {
      const wordKey = path.parse(file.filename).name.split('-')[0];
      return `  '${wordKey}': require('../../assets/audio/${file.relativePath}'),`;
    })
    .join('\n');

  const dictionaryContent = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by scripts/generate-audio-registry.ts
// Run 'npm run map-audio' to regenerate

export const dictionaryAudioMap: Record<string, any> = {
${dictionaryLines}
};

export function normalizeDzKey(input: string): string {
  const lower = input.toLowerCase();
  const stripped = lower.normalize('NFD').replace(/\\p{M}+/gu, '');
  return stripped.replace(/\\s+/g, '_');
}
`;

  await fs.writeFile(path.join(outputDir, 'dictionaryAudio.ts'), dictionaryContent);
  console.log('Generated dictionaryAudio.ts');

  // Summary
  const conversationCount = audioFiles.filter((f) => f.relativePath.startsWith('conversations/')).length;
  console.log('\nSummary:');
  console.log(`  Total audio files: ${audioFiles.length}`);
  console.log(`  Dictionary words: ${dictionaryFiles.length}`);
  console.log(`  Conversations: ${conversationCount}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
